Repository fourThePet/GATE-BackEnd, pull requests merged in 2024-12, with the labels that each got.

#27 feat: [GATE-56] 즐겨찾기 리스트 조회 기능 구현
  src/main/java/com/ureca/gate/favorites/application/FavoritesServiceImpl.java
  src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
  src/main/java/com/ureca/gate/favorites/controller/FavoritesController.java
  src/main/java/com/ureca/gate/favorites/controller/inputport/FavoritesService.java
  src/main/java/com/ureca/gate/favorites/controller/response/FavoritesEnrollResponse.java
  src/main/java/com/ureca/gate/favorites/controller/response/FavoritesResponse.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesJpaRepository.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
Labels: feature

#29 fix: [GATE-32] 장소 리스트 응답 내 위도,경도 추가
  src/main/java/com/ureca/gate/place/controller/response/PlaceResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/dto/PlaceResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustomImpl.java
Labels: fix

#28 feat: [GATE-70] 일정 생성 API
  src/main/java/com/ureca/gate/plan/application/PlanServiceImpl.java
  src/main/java/com/ureca/gate/plan/application/command/PlanCreateCommand.java
  src/main/java/com/ureca/gate/plan/application/outputport/PlanRepository.java
  src/main/java/com/ureca/gate/plan/controller/PlanController.java
  src/main/java/com/ureca/gate/plan/controller/inputport/PlanService.java
  src/main/java/com/ureca/gate/plan/controller/request/PlanSaveRequest.java
  src/main/java/com/ureca/gate/plan/controller/response/PlanResponse.java
  src/main/java/com/ureca/gate/plan/domain/Plan.java
  src/main/java/com/ureca/gate/plan/domain/PlanDog.java
  src/main/java/com/ureca/gate/plan/domain/PlanPlace.java
  src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/PlanJpaRepository.java
  src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/PlanRepositoryImpl.java
  src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/entity/PlanDogEntity.java
  src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/entity/PlanEntity.java
  src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/entity/PlanPlaceEntity.java
  src/test/java/com/ureca/gate/plan/domain/PlanDogTest.java
  src/test/java/com/ureca/gate/plan/domain/PlanPlaceTest.java
  src/test/java/com/ureca/gate/plan/domain/PlanTest.java
Labels: feature

#30 refactor: [GATE-38] 장소 내 즐겨찾기 여부 추가
  src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesJpaRepository.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
  src/main/java/com/ureca/gate/place/application/PlaceDetailServiceImpl.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PlaceDetailService.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceDetailResponse.java
Labels: refactor

#33 refactor: [GATE-38] 장소 리스트 조회 응답값 수정 & 즐겨찾기 여부 조회 로직 FavoritesService…
  src/main/java/com/ureca/gate/favorites/application/FavoritesServiceImpl.java
  src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
  src/main/java/com/ureca/gate/favorites/controller/FavoritesController.java
  src/main/java/com/ureca/gate/favorites/controller/inputport/FavoritesService.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesJpaRepository.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/gate/place/application/PlaceDetailServiceImpl.java
  src/main/java/com/ureca/gate/place/application/PlaceListServiceImpl.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PlaceListService.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/dto/PlaceResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustomImpl.java
Labels: refactor, fix

#34 feat: [GATE-75] 일정 조회 API
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/gate/place/application/outputport/CityRepository.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/CityRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
  src/main/java/com/ureca/gate/plan/application/PlanServiceImpl.java
  src/main/java/com/ureca/gate/plan/application/outputport/PlanRepository.java
  src/main/java/com/ureca/gate/plan/controller/PlanController.java
  src/main/java/com/ureca/gate/plan/controller/inputport/PlanService.java
  src/main/java/com/ureca/gate/plan/controller/response/PlaceInfo.java
  src/main/java/com/ureca/gate/plan/controller/response/PlanPlaceResponse.java
  src/main/java/com/ureca/gate/plan/controller/response/PlanResponse.java
  src/main/java/com/ureca/gate/plan/domain/Plan.java
  src/main/java/com/ureca/gate/plan/domain/PlanPlace.java
  src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/PlanRepositoryImpl.java
  src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/entity/PlanEntity.java
  src/main/java/com/ureca/gate/plan/infrastructure/jpaadapter/entity/PlanPlaceEntity.java
  src/test/java/com/ureca/gate/plan/domain/PlanPlaceTest.java
  src/test/java/com/ureca/gate/plan/domain/PlanTest.java
Labels: feature

#35 refactor: [GATE-56] 즐겨찾기 리스트 조회시 응답값 수정
  src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
  src/main/java/com/ureca/gate/favorites/controller/response/FavoritesResponse.java
  src/main/java/com/ureca/gate/favorites/infrastructure/dto/FavoritesIdWithPlaceDto.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
Labels: refactor

#36 fix: [GATE-44] 리뷰 API 완료
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/gate/review/application/KeywordServiceImpl.java
  src/main/java/com/ureca/gate/review/application/ReviewKeywordServiceImpl.java
  src/main/java/com/ureca/gate/review/application/ReviewServiceImpl.java
  src/main/java/com/ureca/gate/review/application/outputport/KeywordRepository.java
  src/main/java/com/ureca/gate/review/application/outputport/ReviewFileRepository.java
  src/main/java/com/ureca/gate/review/application/outputport/ReviewKeywordRepository.java
  src/main/java/com/ureca/gate/review/application/outputport/ReviewRepository.java
  src/main/java/com/ureca/gate/review/controller/ReviewController.java
  src/main/java/com/ureca/gate/review/controller/inputport/KeywordService.java
  src/main/java/com/ureca/gate/review/controller/inputport/ReviewKeywordService.java
  src/main/java/com/ureca/gate/review/controller/inputport/ReviewService.java
  src/main/java/com/ureca/gate/review/controller/request/ReviewSaveRequest.java
  src/main/java/com/ureca/gate/review/controller/response/KeywordResponse.java
  src/main/java/com/ureca/gate/review/controller/response/PlaceReviewResponse.java
  src/main/java/com/ureca/gate/review/controller/response/ReviewKeywordResponse.java
  src/main/java/com/ureca/gate/review/controller/response/ReviewResponse.java
  src/main/java/com/ureca/gate/review/domain/Keyword.java
  src/main/java/com/ureca/gate/review/domain/Review.java
  src/main/java/com/ureca/gate/review/domain/ReviewFile.java
  src/main/java/com/ureca/gate/review/domain/ReviewKeyword.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/KeywordJpaRepository.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/KeywordRepositoryImpl.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/ReviewFileRepositoryImpl.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/ReviewJpaRepository.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/ReviewKeywordJpaRepository.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/ReviewKeywordRepositoryImpl.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/ReviewRepositoryImpl.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/entity/KeywordEntity.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/entity/ReviewEntity.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/entity/ReviewFileEntity.java
  src/main/java/com/ureca/gate/review/infrasturcture/jpaadapter/entity/ReviewKeywordEntity.java
Labels: feature

#37 fix: [GATE-36] 잘못된 url 수정 및 응답값 재수정
  src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
  src/main/java/com/ureca/gate/favorites/controller/FavoritesController.java
  src/main/java/com/ureca/gate/favorites/controller/response/FavoritesResponse.java
  src/main/java/com/ureca/gate/favorites/infrastructure/dto/FavoritesIdWithPlaceDto.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
Labels: fix

#62 fix : 0.1 스코어 미만은 출력 안 되게끔 수정
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilder.java
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
Labels: fix

#65 fix : 매핑 지역명 수정
  src/main/java/com/ureca/gate/global/util/city/CityMapper.java
Labels: fix

#67 feat: [GATE-88] elasticSearch를 통한 장소 검색 API
  src/main/java/com/ureca/gate/global/util/place/PlaceMapper.java
  src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceElasticRepository.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PlaceForMapService.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceForMapResponse.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceSearchForMapResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/command/PlaceDistanceDto.java
  src/main/java/com/ureca/gate/place/infrastructure/command/PlaceSearchCommand.java
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilders.java
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/Document/PlaceElastic.java
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceJpaRepository.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
  src/main/java/com/ureca/gate/review/application/outputport/GptService.java
  src/main/java/com/ureca/gate/review/infrasturcture/gptadapter/GptServiceImpl.java
Labels: feature

#68 fix: [GATE-88] dto응답값 수정
  src/main/java/com/ureca/gate/place/controller/response/PlaceSearchForMapResponse.java
Labels: fix

#69 fix: [GATE-88] PlaceController-GetPlacesBySearch 메소드 Default Size 설정
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
Labels: fix

#70 fix: [GATE-88] BoolQueryBuilders Class의 가우스 함수 거리 조절 1km -> 0.5km
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilders.java
Labels: fix

#71 fix: [GATE-38] 장소 상세 조회 내 응답값 추가
  src/main/java/com/ureca/gate/place/application/PlaceDetailServiceImpl.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PlaceDetailService.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceDetailResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceJpaRepository.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
Labels: fix

#72 refactor: script_fields를 활용하여 거리(distance) 계산하도록 수정
  src/main/java/com/ureca/gate/global/dto/response/PageResponse.java
  src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PlaceForMapService.java
  src/main/java/com/ureca/gate/place/infrastructure/command/PlaceSearchCommand.java
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/BoolQueryBuilders.java
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceJpaRepository.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
Labels: refactor

#74 fix : 반경 검색시, 잘못된 위치 거리 계산 수정
  src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PlaceForMapService.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustom.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustomImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
Labels: fix

#76 feat: [GATE-73] 일정 최단 경로 API 에러 응답코드 수정
  src/main/java/com/ureca/gate/global/exception/custom/RouteNotFoundException.java
  src/main/java/com/ureca/gate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ureca/gate/plan/application/PlanRouteServiceImpl.java
Labels: refactor

#77 fix : [GATE - 88] 검색어 기반 장소 검색 & 반경 기반 장소 검색 API 통합
  src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceElasticRepository.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PlaceForMapService.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceForMapResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/PlaceElasticRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustom.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustomImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
Labels: fix

#75 Feat/personalize 1
  build.gradle
  src/main/java/com/ureca/gate/global/config/personalize/personalizeConfig.java
  src/main/java/com/ureca/gate/place/application/PersonalizeServiceImpl.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PersonalizeService.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceForPlanResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/command/PlaceForPlanCommand.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceJpaRepository.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/personalizeadpater/PersonalizeRequestBuilder.java
Labels: feature

#78 fix : [GATE-88] Elasticsearch 응답의 _class 필드 무시 처리
  src/main/java/com/ureca/gate/place/infrastructure/elasticsearchadapter/Document/PlaceElastic.java
Labels: fix

#79 fix : 검색어 없이 지역명만 검색시 검색어에 지역명 넣기
  src/main/java/com/ureca/gate/place/application/PlaceForMapServiceImpl.java
Labels: fix
