Repository fourThePet/GATE-BackEnd, pull requests merged in 2024-11, with the labels that each got.

#2 [Feat/1] 공통 응답 통일 구현
  .gitignore
  build.gradle
  src/main/java/com/ureca/gate/TestController.java
  src/main/java/com/ureca/gate/global/entity/BaseEntity.java
  src/main/java/com/ureca/gate/global/entity/BaseTimeEntity.java
  src/main/java/com/ureca/gate/global/exception/BusinessException.java
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/gate/global/exception/errorcode/ErrorCode.java
  src/main/java/com/ureca/gate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ureca/gate/global/response/ApiResponse.java
  src/main/java/com/ureca/gate/global/response/ErrorResponse.java
  src/main/java/com/ureca/gate/global/response/SuccessResponse.java
  src/main/resources/application.properties
Labels: feature

#5 Deploy/3
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
Labels: feature

#6 feat: [GATE-22] 소셜 로그인 API (카카오)
  build.gradle
  src/main/java/com/ureca/gate/GateApplication.java
  src/main/java/com/ureca/gate/TestController.java
  src/main/java/com/ureca/gate/global/config/redis/RedisCacheConfig.java
  src/main/java/com/ureca/gate/global/config/redis/RedisConfig.java
  src/main/java/com/ureca/gate/global/config/security/LoginService.java
  src/main/java/com/ureca/gate/global/config/security/OAuthOIDCHelper.java
  src/main/java/com/ureca/gate/global/config/security/OauthConfig.java
  src/main/java/com/ureca/gate/global/config/security/SecurityConfig.java
  src/main/java/com/ureca/gate/global/config/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/ureca/gate/global/config/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/ureca/gate/global/dto/response/ApiResponse.java
  src/main/java/com/ureca/gate/global/dto/response/ErrorResponse.java
  src/main/java/com/ureca/gate/global/dto/response/SuccessResponse.java
  src/main/java/com/ureca/gate/global/dto/security/OIDCDecodePayload.java
  src/main/java/com/ureca/gate/global/dto/security/OIDCPublicKeyDto.java
  src/main/java/com/ureca/gate/global/dto/security/OIDCPublicKeysResponse.java
  src/main/java/com/ureca/gate/global/exception/custom/BusinessException.java
  src/main/java/com/ureca/gate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ureca/gate/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/ureca/gate/global/infrastructure/cache/CacheRepository.java
  src/main/java/com/ureca/gate/global/infrastructure/cache/RedisRepository.java
  src/main/java/com/ureca/gate/global/util/jwt/JwtOIDCUtil.java
  src/main/java/com/ureca/gate/global/util/jwt/JwtUtil.java
  src/main/java/com/ureca/gate/member/application/AuthenticationServiceImpl.java
  src/main/java/com/ureca/gate/member/application/outputport/KakaoOauthService.java
  src/main/java/com/ureca/gate/member/application/outputport/MemberRepository.java
  src/main/java/com/ureca/gate/member/controller/MemberController.java
  src/main/java/com/ureca/gate/member/controller/MemberRedirectController.java
  src/main/java/com/ureca/gate/member/controller/inputport/AuthenticationService.java
  src/main/java/com/ureca/gate/member/controller/response/UserSignInResponse.java
  src/main/java/com/ureca/gate/member/domain/Enum/Gender.java
  src/main/java/com/ureca/gate/member/domain/Enum/Role.java
  src/main/java/com/ureca/gate/member/domain/Enum/SocialType.java
  src/main/java/com/ureca/gate/member/domain/Member.java
  src/main/java/com/ureca/gate/member/domain/OauthInfo.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaAdapter/Entitiy/MemberEntity.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaAdapter/MemberJpaRepository.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaAdapter/MemberRepositoryImpl.java
  src/main/java/com/ureca/gate/member/infrastructure/oauthAdapter/KakaoOauthClient.java
  src/main/java/com/ureca/gate/member/infrastructure/oauthAdapter/KakaoOauthServiceImpl.java
Labels: feature

#7 feat: [GATE-24] 닉네임 중복체크 API 및 회원 상태 관리 추가
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/gate/member/application/AuthenticationServiceImpl.java
  src/main/java/com/ureca/gate/member/application/MemberServiceImpl.java
  src/main/java/com/ureca/gate/member/application/outputport/MemberRepository.java
  src/main/java/com/ureca/gate/member/controller/MemberController.java
  src/main/java/com/ureca/gate/member/controller/inputport/AuthenticationService.java
  src/main/java/com/ureca/gate/member/controller/inputport/MemberService.java
  src/main/java/com/ureca/gate/member/controller/request/NicknameCheckRequest.java
  src/main/java/com/ureca/gate/member/controller/response/MemberSignInResponse.java
  src/main/java/com/ureca/gate/member/domain/Enum/Status.java
  src/main/java/com/ureca/gate/member/domain/Member.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaAdapter/Entitiy/MemberEntity.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaAdapter/MemberJpaRepository.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaAdapter/MemberRepositoryImpl.java
Labels: feature

#8 feat: [GATE-25] 회원가입 API (추가정보 입력) 구현
  src/main/java/com/ureca/gate/member/application/MemberServiceImpl.java
  src/main/java/com/ureca/gate/member/application/outputport/MemberRepository.java
  src/main/java/com/ureca/gate/member/controller/MemberController.java
  src/main/java/com/ureca/gate/member/controller/inputport/MemberService.java
  src/main/java/com/ureca/gate/member/controller/request/SignUpAddInfoRequest.java
  src/main/java/com/ureca/gate/member/domain/Member.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaAdapter/Entitiy/MemberEntity.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaAdapter/MemberRepositoryImpl.java
Labels: feature

#9 feat: [GATE-84] 로그아웃 구현
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/gate/global/util/redis/CacheKeyUtil.java
  src/main/java/com/ureca/gate/member/application/AuthenticationServiceImpl.java
  src/main/java/com/ureca/gate/member/application/MemberServiceImpl.java
  src/main/java/com/ureca/gate/member/controller/MemberController.java
  src/main/java/com/ureca/gate/member/controller/inputport/AuthenticationService.java
Labels: feature

#10 feat: [GATE-85] 토큰 재발급
  src/main/java/com/ureca/gate/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/ureca/gate/global/util/redis/CacheKeyUtil.java
  src/main/java/com/ureca/gate/member/application/AuthenticationServiceImpl.java
  src/main/java/com/ureca/gate/member/controller/MemberController.java
  src/main/java/com/ureca/gate/member/controller/inputport/AuthenticationService.java
  src/main/java/com/ureca/gate/member/controller/response/TokenReissueResponse.java
Labels: feature

#11 Feat/gate 27 kimjooho create dog profile
  build.gradle
  src/main/java/com/ureca/gate/dog/application/ProfileServiceImpl.java
  src/main/java/com/ureca/gate/dog/application/outputport/DogRepository.java
  src/main/java/com/ureca/gate/dog/controller/ProfileController.java
  src/main/java/com/ureca/gate/dog/controller/inputport/ProfileService.java
  src/main/java/com/ureca/gate/dog/controller/request/ProfileSaveRequest.java
  src/main/java/com/ureca/gate/dog/domain/Dog.java
  src/main/java/com/ureca/gate/dog/domain/enumeration/Gender.java
  src/main/java/com/ureca/gate/dog/domain/enumeration/Size.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/DogJpaRepository.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/DogRepositoryImpl.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/entity/DogEntity.java
  src/main/java/com/ureca/gate/global/config/messageconverter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/ureca/gate/global/config/s3/S3Config.java
  src/main/java/com/ureca/gate/global/util/file/FileStore.java
  src/main/java/com/ureca/gate/global/util/file/UploadFile.java
  src/main/java/com/ureca/gate/global/util/s3/S3Uploader.java
  src/test/java/com/ureca/gate/dog/domain/DogTest.java
Labels: feature

#17 feat: [GATE-38] 시설 정보 조회 API/ 응답값 수정/ CORS 에러 수정
  src/main/java/com/ureca/gate/dog/domain/enumeration/Size.java
  src/main/java/com/ureca/gate/global/config/security/SecurityConfig.java
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaadapter/entity/MemberEntity.java
  src/main/java/com/ureca/gate/place/application/PlaceDetailServiceImpl.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceRepository.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/PlaceDetailService.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceDetailResponse.java
  src/main/java/com/ureca/gate/place/domain/Place.java
  src/main/java/com/ureca/gate/place/domain/enumeration/PetSize.java
  src/main/java/com/ureca/gate/place/domain/enumeration/YesNo.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceJpaRepository.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/PlaceEntity.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/SubCategoryEntity.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/vo/Address.java
Labels: feature, refactor

#18 refactor: cors에러 수정
  src/main/java/com/ureca/gate/global/config/security/SecurityConfig.java
Labels: refactor

#19 refactor: 카테고리와 서브카테고리를 계층 구조로 변환
  src/main/java/com/ureca/gate/place/controller/response/PlaceDetailResponse.java
  src/main/java/com/ureca/gate/place/domain/Category.java
  src/main/java/com/ureca/gate/place/domain/Place.java
  src/main/java/com/ureca/gate/place/domain/SubCategory.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceCategoryJpaRepository.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceCategoryRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/CategoryEntity.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/PlaceEntity.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/SubCategoryEntity.java
Labels: refactor

#20 feat: 반려견 프로필 API & S3 파일 삭제
  src/main/java/com/ureca/gate/dog/application/ProfileServiceImpl.java
  src/main/java/com/ureca/gate/dog/application/outputport/DogRepository.java
  src/main/java/com/ureca/gate/dog/controller/ProfileController.java
  src/main/java/com/ureca/gate/dog/controller/inputport/ProfileService.java
  src/main/java/com/ureca/gate/dog/controller/response/ProfileResponse.java
  src/main/java/com/ureca/gate/dog/domain/Dog.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/DogJpaRepository.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/DogRepositoryImpl.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/entity/DogEntity.java
  src/main/java/com/ureca/gate/global/util/file/FileStorageService.java
  src/main/java/com/ureca/gate/global/util/s3/S3FileManager.java
  src/test/java/com/ureca/gate/dog/domain/DogTest.java
Labels: feature

#23 feat: [GATE-71] 지역리스트 조회 API 구현
  src/main/java/com/ureca/gate/place/application/CityListServiceImpl.java
  src/main/java/com/ureca/gate/place/application/outputport/CityRepository.java
  src/main/java/com/ureca/gate/place/application/outputport/PlaceCategoryRepository.java
  src/main/java/com/ureca/gate/place/controller/PlaceController.java
  src/main/java/com/ureca/gate/place/controller/inputport/CityListService.java
  src/main/java/com/ureca/gate/place/controller/response/CityResponse.java
  src/main/java/com/ureca/gate/place/domain/City.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/CityJpaRepository.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/CityRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceCategoryRepositoryImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/CityEntity.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/vo/Address.java
Labels: feature

#24 feat: [GATE-34] 즐겨찾기 등록 API 구현
  src/main/java/com/ureca/gate/dog/application/ProfileServiceImpl.java
  src/main/java/com/ureca/gate/dog/application/outputport/DogRepository.java
  src/main/java/com/ureca/gate/dog/controller/ProfileController.java
  src/main/java/com/ureca/gate/dog/controller/inputport/ProfileService.java
  src/main/java/com/ureca/gate/dog/domain/Dog.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/DogJpaRepository.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/DogRepositoryImpl.java
  src/main/java/com/ureca/gate/dog/infrastructure/jpaadapter/entity/DogEntity.java
  src/main/java/com/ureca/gate/favorites/application/FavoritesServiceImpl.java
  src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
  src/main/java/com/ureca/gate/favorites/controller/FavoritesController.java
  src/main/java/com/ureca/gate/favorites/controller/inputport/FavoritesService.java
  src/main/java/com/ureca/gate/favorites/controller/request/FavoritesSaveRequest.java
  src/main/java/com/ureca/gate/favorites/controller/response/FavoritesResponse.java
  src/main/java/com/ureca/gate/favorites/domain/Favorites.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesJpaRepository.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/entitiy/FavoritesEntity.java
  src/main/java/com/ureca/gate/global/config/security/SecurityConfig.java
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/gate/member/infrastructure/jpaadapter/entity/MemberEntity.java
  src/main/java/com/ureca/gate/place/controller/response/PlaceDetailResponse.java
  src/main/java/com/ureca/gate/place/domain/Place.java
  src/main/java/com/ureca/gate/place/domain/vo/Address.java
  src/main/java/com/ureca/gate/place/infrastructure/dto/PlaceResponse.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/PlaceRepositoryCustomImpl.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/CityEntity.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/PlaceEntity.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/vo/Address.java
  src/main/java/com/ureca/gate/place/infrastructure/jpaadapter/entity/vo/AddressEntity.java
Labels: feature

#25 feat: [GATE-33] 즐겨찾기 삭제 API 구현
  src/main/java/com/ureca/gate/favorites/application/FavoritesServiceImpl.java
  src/main/java/com/ureca/gate/favorites/application/outputport/FavoritesRepository.java
  src/main/java/com/ureca/gate/favorites/controller/FavoritesController.java
  src/main/java/com/ureca/gate/favorites/controller/inputport/FavoritesService.java
  src/main/java/com/ureca/gate/favorites/domain/Favorites.java
  src/main/java/com/ureca/gate/favorites/domain/enumeration/FavoritesStatus.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesJpaRepository.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/FavoritesRepositoryImpl.java
  src/main/java/com/ureca/gate/favorites/infrastructure/jpaadapter/entitiy/FavoritesEntity.java
  src/main/java/com/ureca/gate/global/exception/errorcode/CommonErrorCode.java
Labels: feature

#26 Hotfix/20241201 jooho dogs
  src/main/java/com/ureca/gate/dog/controller/response/ProfileResponse.java
  src/main/java/com/ureca/gate/dog/domain/Dog.java
  src/main/java/com/ureca/gate/global/util/file/UploadFile.java
  src/test/java/com/ureca/gate/dog/domain/DogTest.java
Labels: bug
